name: deploy to vm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: push to vm
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 194.61.31.176
          username: root
          key: ${{secrets.PRIVATE_KEY}}
          port: 22
          script: |
            cd /root/backend_projects/t3arena_be
            chmod +x deploy.sh
            ./deploy.sh
